INSERT INTO phpbb_adr_alignments (alignment_id, alignment_name, alignment_desc, alignment_level, alignment_img) VALUES (1, 'Adr_alignment_neutral', 'Adr_alignment_neutral_desc', 0, 'Neutral.gif');
INSERT INTO phpbb_adr_alignments (alignment_id, alignment_name, alignment_desc, alignment_level, alignment_img) VALUES (2, 'Adr_alignment_evil', 'Adr_alignment_evil_desc', 0, 'Evil.gif');
INSERT INTO phpbb_adr_alignments (alignment_id, alignment_name, alignment_desc, alignment_level, alignment_img) VALUES (3, 'Adr_alignment_good', 'Adr_alignment_good_desc', 0, 'Good.gif');

INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (1, 'Globuz', 'Monster1.jpg', 1, 15, 30, 30);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (2, 'Kargh', 'Monster2.jpg', 2, 20, 40, 60);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (3, 'Bouglou', 'Monster3.jpg', 1, 14, 40, 70);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (4, 'Dretg', 'Monster4.jpg', 1, 25, 30, 30);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (5, 'Greyiok', 'Monster5.jpg', 1, 10, 70, 70);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (6, 'Itchy', 'Monster6.jpg', 2, 25, 90, 80);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (7, 'Globber', 'Monster7.jpg', 3, 45, 250, 200);
INSERT INTO phpbb_adr_battle_monsters (monster_id, monster_name, monster_img, monster_level, monster_base_hp, monster_base_att, monster_base_def) VALUES (8, 'Scratchy', 'Monster8.jpg', 4, 80, 350, 300);


INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (1, 'Adr_class_fighter', 'Adr_class_fighter_desc', 0, 'Fighter.gif', 0, 0, 0, 0, 0, 0, 30, 2, 15, 3, 0, 1, 1500, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (2, 'Adr_class_barbare', 'Adr_class_barbare_desc', 0, 'Barbare.gif', 12, 0, 10, 0, 0, 0, 40, 1, 10, 4, 0, 0, 2000, 1, 5, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (3, 'Adr_class_druid', 'Adr_class_druid_desc', 0, 'Druid.gif', 0, 0, 0, 0, 10, 0, 20, 20, 10, 1, 2, 2, 1800, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (4, 'Adr_class_bard', 'Adr_class_bard_desc', 0, 'Bard.gif', 3, 3, 3, 3, 3, 10, 15, 15, 15, 2, 2, 2, 1200, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (5, 'Adr_class_magician', 'Adr_class_magician_desc', 0, 'Magician.gif', 0, 0, 0, 14, 14, 0, 8, 30, 5, 0, 1, 3, 2500, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (6, 'Adr_class_monk', 'Adr_class_monk_desc', 0, 'Monk.gif', 5, 5, 5, 5, 5, 5, 25, 10, 20, 2, 2, 1, 2400, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (7, 'Adr_class_paladin', 'Adr_class_paladin_desc', 0, 'Paladin.gif', 10, 8, 10, 10, 8, 15, 40, 15, 20, 2, 4, 1, 3000, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (8, 'Adr_class_priest', 'Adr_class_priest_desc', 0, 'Priest.gif', 0, 0, 0, 10, 12, 0, 20, 20, 15, 1, 2, 2, 2000, 0, 0, 1);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (9, 'Adr_class_sorceror', 'Adr_class_sorceror_desc', 0, 'Sorcerer.gif', 0, 0, 0, 16, 0, 0, 30, 100, 10, 0, 1, 10, 4500, 5, 10, 0);
INSERT INTO phpbb_adr_classes (class_id, class_name, class_desc, class_level, class_img, class_might_req, class_dexterity_req, class_constitution_req, class_intelligence_req, class_wisdom_req, class_charisma_req, class_base_hp, class_base_mp, class_base_ac, class_update_hp, class_update_mp, class_update_ac, class_update_xp_req, class_update_of, class_update_of_req, class_selectable) VALUES (10, 'Adr_class_thief', 'Adr_class_thief_desc', 0, 'Thief.gif', 0, 12, 0, 0, 0, 0, 20, 10, 10, 1, 2, 1, 1500, 0, 0, 1);

INSERT INTO phpbb_adr_elements (element_id, element_name, element_desc, element_level, element_img, element_skill_mining_bonus, element_skill_stone_bonus, element_skill_forge_bonus, element_skill_enchantment_bonus, element_skill_trading_bonus, element_skill_thief_bonus) VALUES (1, 'Adr_element_water', 'Adr_element_water_desc', 0, 'Water.gif', 0, 0, 0, 1, 0, 0);
INSERT INTO phpbb_adr_elements (element_id, element_name, element_desc, element_level, element_img, element_skill_mining_bonus, element_skill_stone_bonus, element_skill_forge_bonus, element_skill_enchantment_bonus, element_skill_trading_bonus, element_skill_thief_bonus) VALUES (2, 'Adr_element_earth', 'Adr_element_earth_desc', 0, 'Earth.gif', 1, 1, 0, 0, 0, 0);
INSERT INTO phpbb_adr_elements (element_id, element_name, element_desc, element_level, element_img, element_skill_mining_bonus, element_skill_stone_bonus, element_skill_forge_bonus, element_skill_enchantment_bonus, element_skill_trading_bonus, element_skill_thief_bonus) VALUES (3, 'Adr_element_holy', 'Adr_element_holy_desc', 2, 'Holy.gif', 1, 1, 1, 1, 1, 1);
INSERT INTO phpbb_adr_elements (element_id, element_name, element_desc, element_level, element_img, element_skill_mining_bonus, element_skill_stone_bonus, element_skill_forge_bonus, element_skill_enchantment_bonus, element_skill_trading_bonus, element_skill_thief_bonus) VALUES (4, 'Adr_element_fire', 'Adr_element_fire_desc', 0, 'Fire.gif', 0, 0, 1, 0, 0, 0);

INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (1, 'Adr_race_human', 'Adr_race_human_desc', 0, 'Human.gif', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (2, 'Adr_race_half-elf', 'Adr_race_half-elf_desc', 0, 'Half-elf.gif', 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (3, 'Adr_race_half-orc', 'Adr_race_half-orc_desc', 0, 'Half-orc.gif', 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 3);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (4, 'Adr_race_elf', 'Adr_race_elf_desc', 0, 'Elf.gif', 0, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (5, 'Adr_race_gnome', 'Adr_race_gnome_desc', 0, 'Gnome.gif', 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (6, 'Adr_race_halfeling', 'Adr_race_halfeling_desc', 2, 'Halfeling.gif', 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 0, 0, 0);
INSERT INTO phpbb_adr_races (race_id, race_name, race_desc, race_level, race_img, race_might_bonus, race_dexterity_bonus, race_constitution_bonus, race_intelligence_bonus, race_wisdom_bonus, race_charisma_bonus, race_skill_mining_bonus, race_skill_stone_bonus, race_skill_forge_bonus, race_skill_enchantment_bonus, race_skill_trading_bonus, race_skill_thief_bonus, race_might_malus, race_dexterity_malus, race_constitution_malus, race_intelligence_malus, race_wisdom_malus, race_charisma_malus) VALUES (7, 'Adr_race_dwarf', 'Adr_race_dwarf_desc', 0, 'Dwarf.gif', 1, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 3);

INSERT INTO phpbb_adr_shops (shop_id, shop_owner_id, shop_name, shop_desc) VALUES (1, 1, 'Adr_shop_forums', 'Adr_shop_forums_desc');

INSERT INTO phpbb_adr_stores(store_id, store_name, store_desc, store_img, store_status, store_sales_status, store_admin) VALUES(1, 'Forum Store', 'The general forum store', '',1 ,0 ,0 );
INSERT INTO phpbb_adr_stores(store_name, store_desc, store_img, store_status, store_sales_status, store_admin) VALUES('Admin Only Store', 'Viewable only by the board admin', '',1 ,0 ,1 );

INSERT INTO `phpbb_adr_shops_items` (`item_id`, `item_owner_id`, `item_price`, `item_quality`, `item_power`, `item_duration`, `item_duration_max`, `item_icon`, `item_name`, `item_desc`, `item_type_use`, `item_in_shop`, `item_store_id`, `item_weight`, `item_auth`, `item_max_skill`, `item_add_power`, `item_mp_use`, `item_monster_thief`, `item_element`, `item_element_str_dmg`, `item_element_same_dmg`, `item_element_weak_dmg`, `item_in_warehouse`, `item_sell_back_percentage`, `item_stolen_id`, `item_steal_dc`, `item_bought_timestamp`, `item_restrict_align_enable`, `item_restrict_align`, `item_restrict_class_enable`, `item_restrict_class`, `item_restrict_element_enable`, `item_restrict_element`, `item_restrict_race_enable`, `item_restrict_race`, `item_restrict_level`, `item_restrict_str`, `item_restrict_dex`, `item_restrict_int`, `item_restrict_wis`, `item_restrict_cha`, `item_restrict_con`, `item_crit_hit`, `item_crit_hit_mod`, `item_stolen_timestamp`, `item_stolen_by`, `item_donated_timestamp`, `item_donated_by`) VALUES 
(11, 1, 27721, 4, 5, 600, 600, 'ring2.gif', 'Adr_items_ring_2', 'Adr_items_ring_2_desc', 14, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(10, 1, 11000, 3, 1, 150, 150, 'ring1.gif', 'Adr_items_ring_1', 'Adr_items_ring_1_desc', 14, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(9, 1, 1078, 4, 3, 1, 1, 'scroll4.gif', 'Adr_items_scroll_4', 'Adr_items_scroll_4_desc', 12, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(8, 1, 550, 3, 1, 1, 1, 'scroll3.gif', 'Adr_items_scroll_3', 'Adr_items_scroll_3_desc', 12, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(7, 1, 100, 3, 10, 10, 10, 'scroll2.gif', 'Adr_items_scroll_2', 'Adr_items_scroll_2_desc', 11, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 50, 0, 0, 0, 0, '0', 1, '3,5,8,9,', 0, '0', 0, '0', 5, 0, 0, 20, 0, 0, 0, 20, 2, 0, '', 0, ''),
(6, 1, 550, 3, 1, 1, 1, 'scroll1.gif', 'Adr_items_scroll_1', 'Adr_items_scroll_1_desc', 11, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(5, 1, 154, 3, 3, 200, 200, 'miner.gif', 'Adr_items_miner', 'Adr_items_miner_desc', 3, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(4, 1, 111, 3, 1, 100, 100, 'tome.gif', 'Adr_item_tome', 'Adr_item_tome_desc', 4, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 1, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(3, 1, 555, 4, 5, 1, 1, 'diamond.gif', 'Adr_items_diamond', 'Adr_items_diamond_desc', 2, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(2, 1, 352, 3, 4, 1, 1, 'sapphire.gif', 'Adr_items_sapphire', 'Adr_items_sapphire_desc', 2, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(1, 1, 56, 3, 1, 1, 1, 'ore.gif', 'Adr_item_ore', 'Adr_item_ore_desc', 1, 0, 1, 25, 0, 25, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0-', 0, '0-', 0, '0-', 0, '0-', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(15, 1, 35, 5, 1, 100, 100, 'armor.gif', 'Armour', '', 7, 0, 1, 10, 0, 15, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(16, 1, 25, 3, 1, 100, 100, 'bracer.gif', 'Tough Shield', '', 8, 0, 1, 10, 0, 15, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(13, 1, 13861, 4, 5, 650, 650, 'amulet2.gif', 'Adr_items_amulet_2', 'Adr_items_amulet_2_desc', 13, 0, 1, 25, 0, 25, 10, 0, 0, 0, 100, 100, 100, 0, 75, 0, 7, 0, 1, '2,3,', 1, '1,2,7,', 0, '0', 0, '0', 7, 0, 0, 15, 15, 0, 0, 20, 2, 0, '', 0, ''),
(17, 1, 15, 1, 1, 100, 100, 'glove.gif', 'Gloves', '', 1, 0, 1, 5, 0, 10, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(14, 1, 25, 4, 1, 100, 100, 'winged-helm.gif', 'Winged Helm', '', 9, 0, 1, 5, 0, 5, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(18, 1, 35, 4, 1, 100, 100, 'sword.gif', 'Sword', '', 5, 0, 1, 5, 0, 10, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(19, 1, 100, 6, 5, 250, 250, 'flail.gif', 'Flail', '', 5, 0, 1, 12, 0, 15, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 3, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(20, 1, 150, 4, 10, 300, 300, 'bow.gif', 'Bow', '', 5, 0, 1, 15, 0, 20, 0, 0, 0, 0, 100, 100, 100, 0, 75, 0, 0, 0, 0, '0', 1, '4,5,9,10,', 0, '0', 1, '1,2,4,', 5, 0, 20, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(21, 1, 10, 1, 10, 5, 5, 'potion1.gif', 'Health Potion', '', 15, 0, 1, 3, 0, 0, 0, 0, 0, 0, 100, 100, 100, 0, 5, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, ''),
(22, 1, 10, 4, 10, 5, 5, 'potion2.gif', 'Mana Potion', '', 16, 0, 1, 3, 0, 0, 0, 0, 0, 0, 100, 100, 100, 0, 5, 0, 0, 0, 0, '0', 0, '0', 0, '0', 0, '0', 0, 0, 0, 0, 0, 0, 0, 20, 2, 0, '', 0, '');

INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (0, 0, 'Adr_dont_care');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (1, 20, 'Adr_items_quality_very_poor');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (2, 50, 'Adr_items_quality_poor');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (3, 100, 'Adr_items_quality_medium');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (4, 140, 'Adr_items_quality_good');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (5, 200, 'Adr_items_quality_very_good');
INSERT INTO phpbb_adr_shops_items_quality (item_quality_id, item_quality_modifier_price, item_quality_lang) VALUES (6, 300, 'Adr_items_quality_excellent');

INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (0, 0, 'Adr_dont_care');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (1, 50, 'Adr_items_type_raw_materials');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (2, 200, 'Adr_items_type_rare_raw_materials');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (3, 100, 'Adr_items_type_tools_pickaxe');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (4, 100, 'Adr_items_type_tools_magictome');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (5, 100, 'Adr_items_type_weapon');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (6, 1000, 'Adr_items_type_enchanted_weapon');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (7, 200, 'Adr_items_type_armor');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (8, 100, 'Adr_items_type_buckler');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (9, 50, 'Adr_items_type_helm');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (10, 50, 'Adr_items_type_gloves');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (11, 500, 'Adr_items_type_magic_attack');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (12, 500, 'Adr_items_type_magic_defend');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (13, 5000, 'Adr_items_type_amulet');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (14, 10000, 'Adr_items_type_ring');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (15, 20, 'Adr_items_type_health_potion');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (16, 20, 'Adr_items_type_mana_potion');
INSERT INTO phpbb_adr_shops_items_type (item_type_id, item_type_base_price, item_type_lang) VALUES (17, 1, 'Adr_items_type_misc');

INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (1, 'Adr_mining', 'Adr_skill_mining_desc', 'skill_mining.gif', 100, 5);
INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (2, 'Adr_stone', 'Adr_skill_stone_desc', 'skill_stone.gif', 200, 5);
INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (3, 'Adr_forge', 'Adr_skill_forge_desc', 'skill_forge.gif', 50, 5);
INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (4, 'Adr_enchantment', 'Adr_skill_enchantment_desc', 'skill_enchantment.gif', 300, 5);
INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (5, 'Adr_trading', 'Adr_skill_trading_desc', 'skill_trading.gif', 80, 5);
INSERT INTO phpbb_adr_skills (skill_id, skill_name, skill_desc, skill_img, skill_req, skill_chance) VALUES (6, 'Adr_thief', 'Adr_skill_thief_desc', 'skill_thief.gif', 70, 5);

INSERT INTO phpbb_adr_vault_exchange (stock_id, stock_name, stock_desc, stock_price, stock_previous_price, stock_best_price, stock_worst_price) VALUES (1, 'Adr_vault_action_name_1', 'Adr_vault_action_desc_1', 113, 108, 113, 100);
INSERT INTO phpbb_adr_vault_exchange (stock_id, stock_name, stock_desc, stock_price, stock_previous_price, stock_best_price, stock_worst_price) VALUES (2, 'Adr_vault_action_name_2', 'Adr_vault_action_desc_2', 177, 192, 200, 177);
INSERT INTO phpbb_adr_vault_exchange (stock_id, stock_name, stock_desc, stock_price, stock_previous_price, stock_best_price, stock_worst_price) VALUES (3, 'Adr_vault_action_name_3', 'Adr_vault_action_desc_3', 280, 288, 300, 280);

